### ISSUE TITLE
"RuntimeError: CUDA out of memory" during feature extraction

### ISSUE THREAD

**Issue by nekosan314** [ando-hub/MSA_Pretrain#2]
Hi Ando, Thanks for this great work.
Now, I want to run the code but some problems happen when I reach the stage of feature extraction.

More concretely, 
When I run /MSA_Pretrain/scripts/extfeat/extract_audio_embedding.py, an error, which is "RuntimeError: CUDA out of memory" always  occur.
I have the four GPU and each has 10GB memory, so I can use them up to 40GB. But this code uses single GPU thus I can't make the best use of it.
But I don't know how to change this code to run multi GPU and how much memory is needed to extract audio feature. 

I only changed data root in /MSA_Pretrain/setup_cmumosei.sh
My enviroment is as follows
python->3.9.1
pytorch->1.12
cuda->1.17

**Comment by ando-hub** [comment]
Thanks for your issue report.
You may solve it to decrease $extfeat_batchsize in `setup_cmumosei.sh` from 4 to 1. extract_audio_embedding.py performs acoustic feature extraction for each of $extfeat_batchsize wavfiles. Please set the lower values to that variable.
If it still doesn't work, you should run feature extraction on CPU; set `gpuid=-1`.

**Comment by ando-hub** [comment]
Can you show me the detailed error log?

**Comment by ando-hub** [comment]
Thank you for reporting the error. 
You may avoid it by setting the environmental variable `PYTORCH_CUDA_ALLOC_CONF`. Please retry after adding the following line in `setup_cmumosei.sh` L2:
```
export PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.6, max_split_size_mb:128
```
The following pages will help you.
https://pytorch.org/docs/stable/notes/cuda.html#memory-management
https://stealthoptional.com/tech/stable-diffusion-runtime-error-how-to-fix-cuda-out-of-memory-error-in-stable-diffusion/

**Comment by ando-hub** [comment]
I may have found the reason.
- There are several audio files with long durations in CMU-MOSEI, which tend to be failed in acoustic feature extraction on GPU. 
- `extract_audio_embedding.py` skips processing those audios by catching `RuntimeError: CUDA out of memory.`. After running it on GPU, you can process all the files by re-running it on the CPU.
- But pytorch 1.12+ will have changed to raise `torch.cuda.OutOfMemoryError` instead of `RuntimeError: CUDA out of memory.`. The script cannot handle this exception, which unexpectedly stops the process.

I'll fix this bug next week. I'm sorry for the inconvenience.

**Comment by nekosan314** [comment]
Oh, I see that the pytorch version is important.

In order to reduce the CPU load  I run `extract_audio_embedding.py` on condition that use GPU and batch_size =1 , then I re-run it on CPU.
Now I'm running the code according to this way, and I think it will work well.

I can't thank you enough for your help!
